### ISSUE TITLE
project images

### ISSUE THREAD

**Issue by wjreckli** [uav4geo/DroneDB#34]
Is there something wrong with this command-

To project an image onto a map:

ddb geoproj images/DJI_0018.JPG -o projected/

the help for geoproj has a different input format.  I recieve an error of 'std::domain_error"

**Comment by pierotofy** [comment]
Hey @wjreckli :hand: thanks for the report. Could you upload your test image somewhere so we can try to reproduce this?

**Comment by wjreckli** [comment]
it is a directory of images,  That was a clip from the readme.  The images import fine but I think there is something wrong with the format of the command.

Thanks for all the work on this tool.  If I can get footprints it will be a big help.

**Comment by pierotofy** [comment]
Can you share the directory (even privately)?

**Comment by wjreckli** [comment]
Just sent you a private share.

**Comment by pierotofy** [comment]
Can confirm, this is a bug.

**Comment by wjreckli** [comment]
How about that.  My first one.

**Comment by pierotofy** [comment]
@wjreckli this should have been fixed. Please update and see if it works for your dataset? Feel free to re-open if the issue is still there. :+1:

**Comment by wjreckli** [comment]
It is working great now.  Thanks.
